In [1]:
import pandas as pd
import numpy as np

In [2]:
import numpy as np

In [3]:
jobs_df = pd.read_csv('postings.csv', low_memory=False)

In [4]:
jobs_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   str
 6   location                    123849 non-null  str
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  str
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  str
 16  application_url             87184 non-null   str
 17  application_type            123849 non-null  str
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   str
 21  skills_desc                 2439 non-null    str
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   str
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  str
 26  currency                    36073 non-null   str
 27  compensation_type           36073 non-null   str
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), str(15)
memory usage: 29.3 MB

In [5]:
jobs_df_clean = jobs_df.copy()

In [6]:
jobs_df_clean

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1.713571e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,NaN,1.713572e+12,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,NaN,1.713572e+12,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1.713573e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [7]:
jobs_df_clean['remote_allowed'].info()

<class 'pandas.Series'>
RangeIndex: 123849 entries, 0 to 123848
Series name: remote_allowed
Non-Null Count  Dtype
--------------  -----
15246 non-null  float64
dtypes: float64(1)
memory usage: 967.7 KB

In [8]:
jobs_df_clean['remote_allowed'] = jobs_df_clean['remote_allowed'].fillna(0)

In [9]:
jobs_df_clean['remote_allowed'].info()

<class 'pandas.Series'>
RangeIndex: 123849 entries, 0 to 123848
Series name: remote_allowed
Non-Null Count   Dtype
--------------   -----
123849 non-null  float64
dtypes: float64(1)
memory usage: 967.7 KB

In [10]:
columns_to_drop = ['closed_time', 'zip_code', 'fips']

In [11]:
jobs_df_clean.drop(columns=columns_to_drop, errors='ignore', inplace=True)

In [12]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   str
 6   location                    123849 non-null  str
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  str
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              123849 non-null  float64
 15  job_posting_url             123849 non-null  str
 16  application_url             87184 non-null   str
 17  application_type            123849 non-null  str
 18  expiry                      123849 non-null  float64
 19  formatted_experience_level  94440 non-null   str
 20  skills_desc                 2439 non-null    str
 21  listed_time                 123849 non-null  float64
 22  posting_domain              83881 non-null   str
 23  sponsored                   123849 non-null  int64
 24  work_type                   123849 non-null  str
 25  currency                    36073 non-null   str
 26  compensation_type           36073 non-null   str
 27  normalized_salary           36073 non-null   float64
dtypes: float64(11), int64(2), str(15)
memory usage: 26.5 MB

In [13]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   str
 6   location                    123849 non-null  str
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  str
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              123849 non-null  float64
 15  job_posting_url             123849 non-null  str
 16  application_url             87184 non-null   str
 17  application_type            123849 non-null  str
 18  expiry                      123849 non-null  float64
 19  formatted_experience_level  94440 non-null   str
 20  skills_desc                 2439 non-null    str
 21  listed_time                 123849 non-null  float64
 22  posting_domain              83881 non-null   str
 23  sponsored                   123849 non-null  int64
 24  work_type                   123849 non-null  str
 25  currency                    36073 non-null   str
 26  compensation_type           36073 non-null   str
 27  normalized_salary           36073 non-null   float64
dtypes: float64(11), int64(2), str(15)
memory usage: 26.5 MB

In [14]:
jobs_df_clean['pay_period'].unique()

<StringArray>
['HOURLY', 'YEARLY', nan, 'MONTHLY', 'WEEKLY', 'BIWEEKLY']
Length: 6, dtype: str

In [15]:
jobs_df_clean['pay_period'] = jobs_df_clean['pay_period'].fillna('Not Specified')

In [16]:
jobs_df_clean['pay_period'].unique()

<StringArray>
['HOURLY', 'YEARLY', 'Not Specified', 'MONTHLY', 'WEEKLY', 'BIWEEKLY']
Length: 6, dtype: str

In [17]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   max_salary                  29793 non-null   float64
 5   pay_period                  123849 non-null  str
 6   location                    123849 non-null  str
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  str
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              123849 non-null  float64
 15  job_posting_url             123849 non-null  str
 16  application_url             87184 non-null   str
 17  application_type            123849 non-null  str
 18  expiry                      123849 non-null  float64
 19  formatted_experience_level  94440 non-null   str
 20  skills_desc                 2439 non-null    str
 21  listed_time                 123849 non-null  float64
 22  posting_domain              83881 non-null   str
 23  sponsored                   123849 non-null  int64
 24  work_type                   123849 non-null  str
 25  currency                    36073 non-null   str
 26  compensation_type           36073 non-null   str
 27  normalized_salary           36073 non-null   float64
dtypes: float64(11), int64(2), str(15)
memory usage: 26.5 MB

In [18]:
jobs_df_clean[['max_salary', 'med_salary', 'min_salary']].info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   max_salary  29793 non-null  float64
 1   med_salary  6280 non-null   float64
 2   min_salary  29793 non-null  float64
dtypes: float64(3)
memory usage: 2.8 MB

In [20]:
jobs_df_clean[['max_salary', 'med_salary', 'min_salary', 'pay_period']]

        max_salary  med_salary  min_salary     pay_period
0             20.0         NaN        17.0         HOURLY
1             50.0         NaN        30.0         HOURLY
2          65000.0         NaN     45000.0         YEARLY
3         175000.0         NaN    140000.0         YEARLY
4          80000.0         NaN     60000.0         YEARLY
...            ...         ...         ...            ...
123844    195000.0         NaN    120000.0         YEARLY
123845         NaN         NaN         NaN  Not Specified
123846         NaN         NaN         NaN  Not Specified
123847         NaN         NaN         NaN  Not Specified
123848     75000.0         NaN     70000.0         YEARLY

[123849 rows x 4 columns]

In [21]:
jobs_df_clean['avg_salary'] = jobs_df_clean['med_salary']

In [22]:
jobs_df_clean['avg_salary'] = jobs_df_clean['avg_salary'].fillna(
    (jobs_df_clean['max_salary'] + jobs_df_clean['min_salary']) / 2
)

In [23]:
jobs_df_clean[['max_salary', 'med_salary', 'min_salary', 'pay_period', 'avg_salary']].head(10)

   max_salary  med_salary  min_salary     pay_period  avg_salary
0        20.0         NaN        17.0         HOURLY        18.5
1        50.0         NaN        30.0         HOURLY        40.0
2     65000.0         NaN     45000.0         YEARLY     55000.0
3    175000.0         NaN    140000.0         YEARLY    157500.0
4     80000.0         NaN     60000.0         YEARLY     70000.0
5        20.0         NaN        14.0         HOURLY        17.0
6    300000.0         NaN     60000.0         YEARLY    180000.0
7    120000.0         NaN     90000.0         YEARLY    105000.0
8         NaN         NaN         NaN  Not Specified         NaN
9         NaN       350.0         NaN        MONTHLY       350.0

In [24]:
def make_annual(row): # Making Annual Salary
    salary = row['avg_salary']
    period = row['pay_period']
    

    if pd.isna(salary):
        return np.nan
        

    if period == 'YEARLY':
        return salary
    elif period == 'HOURLY':
        return salary * 2080
    elif period == 'MONTHLY':
        return salary * 12
    elif period == 'WEEKLY':
        return salary * 52
    elif period == 'BIWEEKLY':
        return salary * 26
    else:
        return salary

jobs_df_clean['annual_salary'] = jobs_df_clean.apply(make_annual, axis=1)

In [25]:
jobs_df_clean[['max_salary', 'med_salary', 'min_salary', 'pay_period', 'avg_salary', 'annual_salary']].head(10)

,max_salary,med_salary,min_salary,pay_period,avg_salary,annual_salary
0,20.0,NaN,17.0,HOURLY,18.5,38480.0
1,50.0,NaN,30.0,HOURLY,40.0,83200.0
2,65000.0,NaN,45000.0,YEARLY,55000.0,55000.0
3,175000.0,NaN,140000.0,YEARLY,157500.0,157500.0
4,80000.0,NaN,60000.0,YEARLY,70000.0,70000.0
5,20.0,NaN,14.0,HOURLY,17.0,35360.0
6,300000.0,NaN,60000.0,YEARLY,180000.0,180000.0
7,120000.0,NaN,90000.0,YEARLY,105000.0,105000.0
8,NaN,NaN,NaN,Not Specified,NaN,NaN
9,NaN,350.0,NaN,MONTHLY,350.0,4200.0

In [26]:
columns_to_drop = ['max_salary', 'min_salary', 'med_salary', 'avg_salary']

jobs_df_clean = jobs_df_clean.drop(columns=columns_to_drop)
jobs_df_clean.head(10)

,job_id,company_name,title,description,pay_period,location,company_id,views,formatted_work_type,applies,...,formatted_experience_level,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,annual_salary
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,HOURLY,"Princeton, NJ",2774458.0,20.0,Full-time,2.0,...,NaN,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,38480.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",HOURLY,"Fort Collins, CO",NaN,1.0,Full-time,NaN,...,NaN,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,83200.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,YEARLY,"Cincinnati, OH",64896719.0,8.0,Full-time,NaN,...,NaN,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,55000.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,YEARLY,"New Hyde Park, NY",766262.0,16.0,Full-time,NaN,...,NaN,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,157500.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,YEARLY,"Burlington, IA",NaN,3.0,Full-time,NaN,...,NaN,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,70000.0
5,91700727,Downtown Raleigh Alliance,Economic Development and Planning Intern,Job summary:The Economic Development & Plannin...,HOURLY,"Raleigh, NC",1481176.0,9.0,Internship,4.0,...,NaN,NaN,1.713456e+12,NaN,0,INTERNSHIP,USD,BASE_SALARY,35360.0,35360.0
6,103254301,Raw Cereal,Producer,Company DescriptionRaw Cereal is a creative de...,YEARLY,United States,81942316.0,7.0,Contract,1.0,...,NaN,NaN,1.712861e+12,NaN,0,CONTRACT,USD,BASE_SALARY,180000.0,180000.0
7,112576855,NaN,Building Engineer,Summary: Due to the pending retirement of our ...,YEARLY,"San Francisco, CA",NaN,2.0,Full-time,NaN,...,NaN,NaN,1.712443e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,105000.0,105000.0
8,1218575,Children's Nebraska,Respiratory Therapist,"At Children’s, the region’s only full-service ...",Not Specified,"Omaha, NE",721189.0,3.0,Full-time,NaN,...,NaN,• Requires the ability to communicate effectiv...,1.712348e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN
9,2264355,Bay West Church,Worship Leader,It is an exciting time to be a part of our chu...,MONTHLY,"Palm Bay, FL",28631247.0,5.0,Part-time,NaN,...,NaN,"Knowledge, Skills and Abilities: 1. Proficient...",1.712456e+12,NaN,0,PART_TIME,USD,BASE_SALARY,4200.0,4200.0

In [27]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 26 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   pay_period                  123849 non-null  str
 5   location                    123849 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       122160 non-null  float64
 8   formatted_work_type         123849 non-null  str
 9   applies                     23320 non-null   float64
 10  original_listed_time        123849 non-null  float64
 11  remote_allowed              123849 non-null  float64
 12  job_posting_url             123849 non-null  str
 13  application_url             87184 non-null   str
 14  application_type            123849 non-null  str
 15  expiry                      123849 non-null  float64
 16  formatted_experience_level  94440 non-null   str
 17  skills_desc                 2439 non-null    str
 18  listed_time                 123849 non-null  float64
 19  posting_domain              83881 non-null   str
 20  sponsored                   123849 non-null  int64
 21  work_type                   123849 non-null  str
 22  currency                    36073 non-null   str
 23  compensation_type           36073 non-null   str
 24  normalized_salary           36073 non-null   float64
 25  annual_salary               36073 non-null   float64
dtypes: float64(9), int64(2), str(15)
memory usage: 24.6 MB

In [28]:
jobs_df_clean = jobs_df_clean.drop(columns=['annual_salary', 'compensation_type'])

In [29]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   pay_period                  123849 non-null  str
 5   location                    123849 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       122160 non-null  float64
 8   formatted_work_type         123849 non-null  str
 9   applies                     23320 non-null   float64
 10  original_listed_time        123849 non-null  float64
 11  remote_allowed              123849 non-null  float64
 12  job_posting_url             123849 non-null  str
 13  application_url             87184 non-null   str
 14  application_type            123849 non-null  str
 15  expiry                      123849 non-null  float64
 16  formatted_experience_level  94440 non-null   str
 17  skills_desc                 2439 non-null    str
 18  listed_time                 123849 non-null  float64
 19  posting_domain              83881 non-null   str
 20  sponsored                   123849 non-null  int64
 21  work_type                   123849 non-null  str
 22  currency                    36073 non-null   str
 23  normalized_salary           36073 non-null   float64
dtypes: float64(8), int64(2), str(14)
memory usage: 22.7 MB

In [30]:
jobs_df_clean[['work_type', 'formatted_work_type']].head(10)

    work_type formatted_work_type
0   FULL_TIME           Full-time
1   FULL_TIME           Full-time
2   FULL_TIME           Full-time
3   FULL_TIME           Full-time
4   FULL_TIME           Full-time
5  INTERNSHIP          Internship
6    CONTRACT            Contract
7   FULL_TIME           Full-time
8   FULL_TIME           Full-time
9   PART_TIME           Part-time

In [31]:
jobs_df_clean = jobs_df_clean.drop(columns=['work_type'])

In [32]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   pay_period                  123849 non-null  str
 5   location                    123849 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       122160 non-null  float64
 8   formatted_work_type         123849 non-null  str
 9   applies                     23320 non-null   float64
 10  original_listed_time        123849 non-null  float64
 11  remote_allowed              123849 non-null  float64
 12  job_posting_url             123849 non-null  str
 13  application_url             87184 non-null   str
 14  application_type            123849 non-null  str
 15  expiry                      123849 non-null  float64
 16  formatted_experience_level  94440 non-null   str
 17  skills_desc                 2439 non-null    str
 18  listed_time                 123849 non-null  float64
 19  posting_domain              83881 non-null   str
 20  sponsored                   123849 non-null  int64
 21  currency                    36073 non-null   str
 22  normalized_salary           36073 non-null   float64
dtypes: float64(8), int64(2), str(13)
memory usage: 21.7 MB

In [33]:
jobs_df_clean['listed_time'] = pd.to_datetime(jobs_df_clean['listed_time'], unit='ms')

In [34]:
jobs_df_clean['listed_time'].head(10)

0   2024-04-17 23:45:08
1   2024-04-11 17:51:27
2   2024-04-16 14:26:54
3   2024-04-12 04:23:32
4   2024-04-18 14:52:23
5   2024-04-18 16:01:39
6   2024-04-11 18:43:39
7   2024-04-06 22:44:12
8   2024-04-05 20:21:40
9   2024-04-07 02:12:35
Name: listed_time, dtype: datetime64[ms]

In [35]:
jobs_df_clean['listed_time'] = jobs_df_clean['listed_time'].dt.date

In [36]:
jobs_df_clean['listed_time'].head(10)

0    2024-04-17
1    2024-04-11
2    2024-04-16
3    2024-04-12
4    2024-04-18
5    2024-04-18
6    2024-04-11
7    2024-04-06
8    2024-04-05
9    2024-04-07
Name: listed_time, dtype: object

In [37]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   pay_period                  123849 non-null  str
 5   location                    123849 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       122160 non-null  float64
 8   formatted_work_type         123849 non-null  str
 9   applies                     23320 non-null   float64
 10  original_listed_time        123849 non-null  float64
 11  remote_allowed              123849 non-null  float64
 12  job_posting_url             123849 non-null  str
 13  application_url             87184 non-null   str
 14  application_type            123849 non-null  str
 15  expiry                      123849 non-null  float64
 16  formatted_experience_level  94440 non-null   str
 17  skills_desc                 2439 non-null    str
 18  listed_time                 123849 non-null  object
 19  posting_domain              83881 non-null   str
 20  sponsored                   123849 non-null  int64
 21  currency                    36073 non-null   str
 22  normalized_salary           36073 non-null   float64
dtypes: float64(7), int64(2), object(1), str(13)
memory usage: 21.7+ MB

In [38]:
columns_to_drop = ['original_listed_time', 'job_posting_url', 'application_url', 'expiry', 'skills_desc']
jobs_df_clean.drop(columns=columns_to_drop)

,job_id,company_name,title,description,pay_period,location,company_id,views,formatted_work_type,applies,remote_allowed,application_type,formatted_experience_level,listed_time,posting_domain,sponsored,currency,normalized_salary
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,HOURLY,"Princeton, NJ",2774458.0,20.0,Full-time,2.0,0.0,ComplexOnsiteApply,NaN,2024-04-17,NaN,0,USD,38480.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",HOURLY,"Fort Collins, CO",NaN,1.0,Full-time,NaN,0.0,ComplexOnsiteApply,NaN,2024-04-11,NaN,0,USD,83200.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,YEARLY,"Cincinnati, OH",64896719.0,8.0,Full-time,NaN,0.0,ComplexOnsiteApply,NaN,2024-04-16,NaN,0,USD,55000.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,YEARLY,"New Hyde Park, NY",766262.0,16.0,Full-time,NaN,0.0,ComplexOnsiteApply,NaN,2024-04-12,NaN,0,USD,157500.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,YEARLY,"Burlington, IA",NaN,3.0,Full-time,NaN,0.0,ComplexOnsiteApply,NaN,2024-04-18,NaN,0,USD,70000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,YEARLY,"Walnut Creek, CA",56120.0,1.0,Full-time,NaN,0.0,ComplexOnsiteApply,Mid-Senior level,2024-04-20,NaN,0,USD,157500.0
123845,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,Not Specified,United States,1124131.0,3.0,Full-time,NaN,1.0,OffsiteApply,Mid-Senior level,2024-04-20,www.pinterestcareers.com,0,NaN,NaN
123846,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,Not Specified,"Spokane, WA",90552133.0,3.0,Full-time,NaN,1.0,OffsiteApply,Mid-Senior level,2024-04-20,epsoperations.bamboohr.com,0,NaN,NaN
123847,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,Not Specified,"Texas, United States",2793699.0,4.0,Full-time,NaN,1.0,ComplexOnsiteApply,NaN,2024-04-20,NaN,0,NaN,NaN
123848,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,Full-time,NaN,0.0,ComplexOnsiteApply,Mid-Senior level,2024-04-20,NaN,0,USD,72500.0

In [39]:
columns_to_drop = ['original_listed_time', 'job_posting_url', 'application_url', 'expiry', 'skills_desc']
jobs_df_clean = jobs_df_clean.drop(columns=columns_to_drop)

In [40]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   pay_period                  123849 non-null  str
 5   location                    123849 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       122160 non-null  float64
 8   formatted_work_type         123849 non-null  str
 9   applies                     23320 non-null   float64
 10  remote_allowed              123849 non-null  float64
 11  application_type            123849 non-null  str
 12  formatted_experience_level  94440 non-null   str
 13  listed_time                 123849 non-null  object
 14  posting_domain              83881 non-null   str
 15  sponsored                   123849 non-null  int64
 16  currency                    36073 non-null   str
 17  normalized_salary           36073 non-null   float64
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 17.0+ MB

In [41]:
jobs_df_clean['views'] = jobs_df_clean['views'].fillna(0)
jobs_df_clean['applies'] = jobs_df_clean['applies'].fillna(0)
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   pay_period                  123849 non-null  str
 5   location                    123849 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       123849 non-null  float64
 8   formatted_work_type         123849 non-null  str
 9   applies                     123849 non-null  float64
 10  remote_allowed              123849 non-null  float64
 11  application_type            123849 non-null  str
 12  formatted_experience_level  94440 non-null   str
 13  listed_time                 123849 non-null  object
 14  posting_domain              83881 non-null   str
 15  sponsored                   123849 non-null  int64
 16  currency                    36073 non-null   str
 17  normalized_salary           36073 non-null   float64
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 17.0+ MB

In [43]:
columns_to_fill = ['currency', 'posting_domain', 'formatted_experience_level']

for col in columns_to_fill:
    jobs_df_clean[col] = jobs_df_clean[col].fillna('Not Specified')

In [44]:
columns_to_fill = ['currency', 'posting_domain', 'formatted_experience_level']

for col in columns_to_fill:
    jobs_df_clean[col] = jobs_df_clean[col].fillna('Not Specified')
jobs_df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       123849 non-null  str
 3   description                 123842 non-null  str
 4   pay_period                  123849 non-null  str
 5   location                    123849 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       123849 non-null  float64
 8   formatted_work_type         123849 non-null  str
 9   applies                     123849 non-null  float64
 10  remote_allowed              123849 non-null  float64
 11  application_type            123849 non-null  str
 12  formatted_experience_level  123849 non-null  str
 13  listed_time                 123849 non-null  object
 14  posting_domain              123849 non-null  str
 15  sponsored                   123849 non-null  int64
 16  currency                    123849 non-null  str
 17  normalized_salary           36073 non-null   float64
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 17.0+ MB

In [45]:
jobs_df_clean = jobs_df_clean.dropna(subset=['company_id'])
jobs_df_clean.info()

<class 'pandas.DataFrame'>
Index: 122132 entries, 0 to 123848
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122132 non-null  int64
 1   company_name                122130 non-null  str
 2   title                       122132 non-null  str
 3   description                 122126 non-null  str
 4   pay_period                  122132 non-null  str
 5   location                    122132 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       122132 non-null  float64
 8   formatted_work_type         122132 non-null  str
 9   applies                     122132 non-null  float64
 10  remote_allowed              122132 non-null  float64
 11  application_type            122132 non-null  str
 12  formatted_experience_level  122132 non-null  str
 13  listed_time                 122132 non-null  object
 14  posting_domain              122132 non-null  str
 15  sponsored                   122132 non-null  int64
 16  currency                    122132 non-null  str
 17  normalized_salary           35564 non-null   float64
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 17.7+ MB

In [46]:
jobs_df_clean['company_name'] = jobs_df_clean['company_name'].fillna('Unknown')
jobs_df_clean.info()

<class 'pandas.DataFrame'>
Index: 122132 entries, 0 to 123848
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122132 non-null  int64
 1   company_name                122132 non-null  str
 2   title                       122132 non-null  str
 3   description                 122126 non-null  str
 4   pay_period                  122132 non-null  str
 5   location                    122132 non-null  str
 6   company_id                  122132 non-null  float64
 7   views                       122132 non-null  float64
 8   formatted_work_type         122132 non-null  str
 9   applies                     122132 non-null  float64
 10  remote_allowed              122132 non-null  float64
 11  application_type            122132 non-null  str
 12  formatted_experience_level  122132 non-null  str
 13  listed_time                 122132 non-null  object
 14  posting_domain              122132 non-null  str
 15  sponsored                   122132 non-null  int64
 16  currency                    122132 non-null  str
 17  normalized_salary           35564 non-null   float64
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 17.7+ MB

In [47]:
jobs_df_clean = jobs_df_clean.drop(columns=['description'])
jobs_df_clean.info()

<class 'pandas.DataFrame'>
Index: 122132 entries, 0 to 123848
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122132 non-null  int64
 1   company_name                122132 non-null  str
 2   title                       122132 non-null  str
 3   pay_period                  122132 non-null  str
 4   location                    122132 non-null  str
 5   company_id                  122132 non-null  float64
 6   views                       122132 non-null  float64
 7   formatted_work_type         122132 non-null  str
 8   applies                     122132 non-null  float64
 9   remote_allowed              122132 non-null  float64
 10  application_type            122132 non-null  str
 11  formatted_experience_level  122132 non-null  str
 12  listed_time                 122132 non-null  object
 13  posting_domain              122132 non-null  str
 14  sponsored                   122132 non-null  int64
 15  currency                    122132 non-null  str
 16  normalized_salary           35564 non-null   float64
dtypes: float64(5), int64(2), object(1), str(9)
memory usage: 16.8+ MB

In [48]:
jobs_df_clean['listed_time'] = pd.to_datetime(jobs_df_clean['listed_time'])
jobs_df_clean.info()

<class 'pandas.DataFrame'>
Index: 122132 entries, 0 to 123848
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122132 non-null  int64
 1   company_name                122132 non-null  str
 2   title                       122132 non-null  str
 3   pay_period                  122132 non-null  str
 4   location                    122132 non-null  str
 5   company_id                  122132 non-null  float64
 6   views                       122132 non-null  float64
 7   formatted_work_type         122132 non-null  str
 8   applies                     122132 non-null  float64
 9   remote_allowed              122132 non-null  float64
 10  application_type            122132 non-null  str
 11  formatted_experience_level  122132 non-null  str
 12  listed_time                 122132 non-null  datetime64[s]
 13  posting_domain              122132 non-null  str
 14  sponsored                   122132 non-null  int64
 15  currency                    122132 non-null  str
 16  normalized_salary           35564 non-null   float64
dtypes: datetime64[s](1), float64(5), int64(2), str(9)
memory usage: 16.8 MB

In [49]:
jobs_df_clean['listed_time'].head(10)

0    2024-04-17
2    2024-04-16
3    2024-04-12
5    2024-04-18
6    2024-04-11
8    2024-04-05
9    2024-04-07
10   2024-04-15
11   2024-04-11
14   2024-04-19
Name: listed_time, dtype: datetime64[s]

In [ ]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
Index: 122132 entries, 0 to 123848
Data columns (total 17 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122132 non-null  int64
 1   company_name                122132 non-null  str
 2   title                       122132 non-null  str
 3   pay_period                  122132 non-null  str
 4   location                    122132 non-null  str
 5   company_id                  122132 non-null  float64
 6   views                       122132 non-null  float64
 7   formatted_work_type         122132 non-null  str
 8   applies                     122132 non-null  float64
 9   remote_allowed              122132 non-null  float64
 10  application_type            122132 non-null  str
 11  formatted_experience_level  122132 non-null  str
 12  listed_time                 122132 non-null  datetime64[s]
 13  posting_domain              122132 non-null  str
 14  sponsored                   122132 non-null  int64
 15  currency                    122132 non-null  str
 16  normalized_salary           35564 non-null   float64
dtypes: datetime64[s](1), float64(5), int64(2), str(9)
memory usage: 16.8 MB

In [54]:
jobs_df_clean = jobs_df_clean.drop(columns=['listed_time'])

In [55]:
jobs_df_clean.info()

<class 'pandas.DataFrame'>
Index: 122132 entries, 0 to 123848
Data columns (total 16 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122132 non-null  int64
 1   company_name                122132 non-null  str
 2   title                       122132 non-null  str
 3   pay_period                  122132 non-null  str
 4   location                    122132 non-null  str
 5   company_id                  122132 non-null  float64
 6   views                       122132 non-null  float64
 7   formatted_work_type         122132 non-null  str
 8   applies                     122132 non-null  float64
 9   remote_allowed              122132 non-null  float64
 10  application_type            122132 non-null  str
 11  formatted_experience_level  122132 non-null  str
 12  posting_domain              122132 non-null  str
 13  sponsored                   122132 non-null  int64
 14  currency                    122132 non-null  str
 15  normalized_salary           35564 non-null   float64
dtypes: float64(5), int64(2), str(9)
memory usage: 15.8 MB

In [56]:
jobs_df_clean.to_csv('LinkedIn_Jobs_Cleaned_Final_Final.csv', index=False)